export const colours = {
  white: '#fff',
  black: '#000',
  errorRed: '#cc0000',
  warningAmber: '#ffbf00',
  infoGreen: '#00703c',
  background: {
    weekViewPurple: '#7f53ac',
    weekViewBlue: '#647dee',
    modalTeal: '#377d73',
    backgroundGrey: '#2b2d2f',
    darkGrey: '#9b9797',
    backgroundWhite: '#fffff7',
    loginButton: '#4db6ac',
    loginButtonHover: '#46627f',
    hoverGrey: '#f1f1f1',
    whitesmoke: '#f5f5f5',
    mealCardBlue: '#e6fcff',
  },
  text: { pink: 'hotpink' },
};
